export const Project=[
    {
        Title:"Heritage Website",
        Funtion:"Loan Application Demo",
        Info:" A web app for loan application. it able to store users data and users are able to login and out of the application. When logged in it contains a notification bar and form pages",
        Tech:["React","Tailwind","Node js","Express","Heroku","Mongo DB","Infinityfreehost"],
        Website:"http://heritageloans.ml",
        Github:"https://github.com/Jonahjohnzon/Bank",
        image:"/Image/heritage.png",
        id:1,
        side:"flex-start",
        content:0,
        contents:null,
        text:'right',
        sides:"flex-end",
    },{
        Title:"First portfolio",
        Funtion:"Showcasting my old projects",
        Info:" A web app to show some of my earliest projects. It shows were i started from and how far i have come. It was my introduction to integrating 3d effect into web applications",
        Tech:["React","Tailwind","Three.js","Netlify"],
        Website:"https://jonahominyi.netlify.app/",
        Github:"https://github.com/Jonahjohnzon/Myportfolio",
        image:"/Image/portfolio.png",
        id:2,
        side:"flex-end",
        content:null,
        text:"left",
        contents:0,
        sides:"flex-start",
    },
    {
        Title:"House of Games Website",
        Funtion:" Gaming Site Demo",
        Info:" A web app for loan application.Its a website that links users to the offically site of various games.It was built with a Free Rest Api",
        Tech:["React","Scss","GamesApi","Netlify"],
        Website:"https://hogz.netlify.app/",
        Github:"https://github.com/Jonahjohnzon/Houseof-Games",
        image:"/Image/hogz.png",
        id:3,
        side:"flex-start",
        content:0,
        contents:null,
        text:'right',
        sides:"flex-end",
    },
    {
        Title:"New Portfolio",
        Funtion:"Display some of my projects",
        Info:"A web app to show's some of my projects. It contains link to my social media accounts and github repository . It also contain links to contact me",
        Tech:["React","Tailwind","Infinityfreehost","Framermotion"],
        Website:"https://www.jonahominyi.ml/",
        Github:"https://github.com/Jonahjohnzon/newport",
        image:"/Image/np.png",
        id:4,
        side:"flex-end",
        content:null,
        text:"left",
        contents:0,
        sides:"flex-start",
    },
]
export const Mobile=[
    {
        Title:"Heritage App",
        Funtion:"Loan Mobile Application Demo",
        Info:" An android mobile app for loan application. it able to store users data and users are able to login and out of the application. When logged in it contains a notification bar and form pages",
        Tech:["Dart","Flutter","Node js","Express","Heroku","Mongo DB"],
        Download:"http://heritageloans.ml",
        Github:"https://github.com/Jonahjohnzon/Bank",
        image:"/Image/heritages.png",
        flexact:"row-reverse",
        Website:"https://drive.google.com/file/d/1d1g5Q9-WkRHat55aCfPqWSStd-z2ka_z/view?usp=share_link"
    },{
        Title:"Mimomi",
        Funtion:"Blog Mobile App",
        Info:" A mobile blog app for users to share beliefs,posts and create articles. It contain's a profile page and notification page.",
        Tech:["React Native","Node js","Express","Heroku","Mongo DB"],
        Website:"https://jonahominyi.netlify.app/",
        Github:"https://github.com/Jonahjohnzon/Nimo-App",
        image:"/Image/mimomi.png",
        flexact:"row",
        Website:"https://drive.google.com/file/d/1OMg_o2xV7_z0BUuExH9Ldpt5TlysIoIL/view?usp=share_link"
        
    }
]